import { firebaseConfig, firebaseReady } from './firebase-config.js';
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="assets/visual-settings.css">');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];let auth,db,storage,FS,ST,user,profile={},rows={announcements:[],news:[],events:[],modules:[],quickLinks:[],activities:[],users:[]};
const aliases={teacher:'guru',pkpentadbiran:'pk_pentadbiran',pkkurikulum:'pk_kurikulum',pkkoku:'pk_kokurikulum',pkhem:'pk_hem'};const role=()=>aliases[profile.role]||profile.role||'guru';
const defaultModules={
  pentadbiran:[['🏢','Carta Organisasi','Struktur kepimpinan dan pengurusan sekolah.'],['📅','Takwim Sekolah','Takwim rasmi program dan urusan pentadbiran.'],['📜','Pekeliling','Maklumat pekeliling dan arahan semasa.'],['📥','Muat Turun Borang','Borang awam dan bahan rujukan sekolah.']],
  kurikulum:[['📚','Panitia','Maklumat panitia mata pelajaran.'],['📊','PBD','Pentaksiran Bilik Darjah dan maklumat berkaitan.'],['🏃','SEGAK','Standard Kecergasan Fizikal Kebangsaan untuk Murid Sekolah Malaysia.'],['🤝','PLC','Komuniti Pembelajaran Profesional guru.'],['🎓','Program Akademik','Program peningkatan dan kecemerlangan akademik.'],['🗓️','Jadual Waktu','Maklumat jadual waktu sekolah.'],['📝','Pentaksiran','Maklumat pentaksiran dan penilaian akademik.']],
  kokurikulum:[['📈','PAJSK','Pentaksiran Aktiviti Jasmani, Sukan dan Kokurikulum.'],['🎖️','Unit Beruniform','Aktiviti dan maklumat unit beruniform.'],['👥','Kelab & Persatuan','Aktiviti kelab dan persatuan sekolah.'],['⚽','Sukan & Permainan','Aktiviti sukan dan permainan.'],['🏆','Kejohanan','Penyertaan dan pencapaian kejohanan.']],
  hem:[['🤲','Kebajikan','Maklumat kebajikan dan bantuan murid.'],['📖','SPBT','Pengurusan Skim Pinjaman Buku Teks.'],['🍽️','RMT','Pengurusan Rancangan Makanan Tambahan.'],['❤️','Kesihatan','Program kesihatan dan kesejahteraan murid.'],['💬','Bimbingan & Kaunseling','Perkhidmatan bimbingan dan kaunseling.'],['🛡️','3K','Kebersihan, kesihatan dan keselamatan sekolah.']]
};
const caps=()=>({site:['admin','gb','pk_pentadbiran'].includes(role()),content:['admin','gb','pk_pentadbiran','pk_kurikulum','pk_kokurikulum','pk_hem'].includes(role()),modules:['admin','gb','pk_pentadbiran','pk_kurikulum','pk_kokurikulum','pk_hem'].includes(role()),users:role()==='admin'});
const sectionAllowed=s=>['admin','gb'].includes(role())||(role()==='pk_pentadbiran'&&['pentadbiran','kurikulum'].includes(s))||role()===`pk_${s}`;
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const toast=m=>{const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),3500)};const when=x=>x?.toDate?x.toDate():x?.seconds?new Date(x.seconds*1000):new Date(x||Date.now());
if(!firebaseReady){$('#setupWarning').classList.remove('hidden');$('#loginForm button').disabled=true}
async function init(){if(!firebaseReady)return;try{const appMod=await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js'),authMod=await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js');FS=await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js');ST=await import('https://www.gstatic.com/firebasejs/12.0.0/firebase-storage.js');const app=appMod.initializeApp(firebaseConfig);auth=authMod.getAuth(app);db=FS.getFirestore(app);storage=ST.getStorage(app);$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await authMod.signInWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch{toast('Log masuk gagal. Semak e-mel dan kata laluan.')}});$('#logoutBtn').addEventListener('click',()=>authMod.signOut(auth));authMod.onAuthStateChanged(auth,loadUser);bindForms()}catch(e){toast('Firebase tidak dapat dimulakan: '+e.message)}}
async function loadUser(u){if(!u){user=null;$('#loginPanel').classList.remove('hidden');$('#dashboardPanel').classList.add('hidden');return}user=u;try{const s=await FS.getDoc(FS.doc(db,'users',u.uid));profile=s.exists()?s.data():{};if(profile.status!=='active')throw new Error('Akaun belum diaktifkan oleh pentadbir.');$('#userLabel').textContent=`${profile.name||u.email} · ${role()}`;$('#loginPanel').classList.add('hidden');$('#dashboardPanel').classList.remove('hidden');applyCaps();subscribe()}catch(e){toast(e.message);await auth.signOut()}}
function applyCaps(){const c=caps();$$('[data-cap]').forEach(el=>el.classList.toggle('hidden',!c[el.dataset.cap]));$$('#moduleSection option,#actSection option').forEach(o=>{if(role().startsWith('pk_'))o.disabled=!sectionAllowed(o.value)});$('#seedModulesBox')?.classList.toggle('hidden',!['admin','gb'].includes(role()))}
function bindForms(){$('#settingsForm').addEventListener('submit',saveSettings);$('#contentForm').addEventListener('submit',saveContent);$('#clearContent').addEventListener('click',resetContent);$('#eventForm').addEventListener('submit',saveEvent);$('#moduleForm').addEventListener('submit',saveModule);$('#quickForm').addEventListener('submit',saveQuick);$('#activityForm').addEventListener('submit',saveActivity);$('#userForm').addEventListener('submit',saveUser);const media=['logo','banner','pentadbiranBanner','kurikulumBanner','kokurikulumBanner','hemBanner','flag','plan'];media.forEach(key=>$(`#${key}File`)?.addEventListener('change',e=>{const f=e.target.files[0],preview=$(`#${key}Preview`);if(f&&preview){preview.src=URL.createObjectURL(f);preview.classList.remove('hidden')}}));$('#heroOverlay')?.addEventListener('input',e=>$('#overlayValue').textContent=`${e.target.value}%`)}
const stamp=()=>({updatedAt:FS.serverTimestamp(),updatedBy:user.uid});async function upsert(col,id,data){if(id)await FS.updateDoc(FS.doc(db,col,id),{...data,...stamp()});else await FS.addDoc(FS.collection(db,col),{...data,...stamp(),createdAt:FS.serverTimestamp(),createdBy:user.uid})}
async function upload(file,path){if(!file)return null;if(file.size>5*1024*1024)throw new Error('Saiz fail melebihi 5MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Gunakan gambar JPG, PNG atau WebP.');const ref=ST.ref(storage,path);await ST.uploadBytes(ref,file,{contentType:file.type});return {url:await ST.getDownloadURL(ref),path:ref.fullPath}}
async function saveSettings(e){e.preventDefault();const button=e.submitter;if(button){button.disabled=true;button.textContent='Sedang menyimpan...'}try{const media={};const uploads=[['logo','logo'],['banner','banner'],['pentadbiranBanner','pentadbiran-banner'],['kurikulumBanner','kurikulum-banner'],['kokurikulumBanner','kokurikulum-banner'],['hemBanner','hem-banner'],['flag','bendera'],['plan','pelan']];for(const [key,fileName] of uploads){const file=$(`#${key}File`)?.files[0];if(file){const r=await upload(file,`site/${fileName}-${Date.now()}`);media[`${key}Url`]=r.url;media[`${key}Path`]=r.path}}await FS.setDoc(FS.doc(db,'settings','site'),{schoolName:$('#schoolName').value.trim(),tagline:$('#tagline').value.trim(),motto:$('#motto').value.trim(),facebookUrl:$('#facebookUrl').value.trim(),phone:$('#phone').value.trim(),email:$('#schoolEmail').value.trim(),address:$('#address').value.trim(),vision:$('#vision').value.trim(),mission:$('#mission').value.trim(),primaryColor:$('#primaryColor').value,secondaryColor:$('#secondaryColor').value,accentColor:$('#accentColor').value,heroOverlay:Number($('#heroOverlay').value||65),...media,...stamp()},{merge:true});toast('Profil dan paparan portal disimpan.');e.target.querySelectorAll('input[type=file]').forEach(x=>x.value='')}catch(e){toast(e.message)}finally{if(button){button.disabled=false;button.textContent='Simpan Profil & Paparan'}}}
async function saveContent(e){e.preventDefault();try{await upsert($('#contentType').value,$('#contentId').value,{title:$('#contentTitle').value.trim(),...($('#contentType').value==='news'?{summary:$('#contentBody').value.trim()}:{body:$('#contentBody').value.trim()}),published:$('#contentPublished').checked});resetContent();toast('Kandungan disimpan.')}catch(e){toast(e.message)}}function resetContent(){$('#contentForm').reset();$('#contentId').value='';$('#contentPublished').checked=true}
async function saveEvent(e){e.preventDefault();try{await upsert('events',$('#eventId').value,{title:$('#eventTitle').value.trim(),description:$('#eventDescription').value.trim(),eventDate:$('#eventDate').value,published:$('#eventPublished').checked});e.target.reset();$('#eventId').value='';toast('Takwim disimpan.')}catch(e){toast(e.message)}}
async function saveModule(e){e.preventDefault();const section=$('#moduleSection').value;if(!sectionAllowed(section))return toast('Anda tidak dibenarkan mengurus bahagian ini.');try{await upsert('modules',$('#moduleId').value,{section,title:$('#moduleTitle').value.trim(),description:$('#moduleDescription').value.trim(),content:$('#moduleContent')?.value.trim()||'',icon:$('#moduleIcon').value.trim()||'•',url:$('#moduleUrl').value.trim(),order:Number($('#moduleOrder').value||0),active:$('#moduleActive').checked});e.target.reset();$('#moduleId').value='';$('#moduleActive').checked=true;toast('Kad dashboard dan kandungan disimpan.')}catch(e){toast(e.message)}}
async function saveQuick(e){e.preventDefault();try{await upsert('quickLinks',$('#quickId').value,{label:$('#quickLabel').value.trim(),url:$('#quickUrl').value.trim(),icon:$('#quickIcon').value.trim()||'🔗',order:Number($('#quickOrder').value||0),active:$('#quickActive').checked});e.target.reset();$('#quickId').value='';$('#quickActive').checked=true;toast('Pautan disimpan.')}catch(e){toast(e.message)}}
async function saveActivity(e){e.preventDefault();try{const f=$('#activityImage').files[0];if(!f)throw new Error('Pilih gambar dahulu.');const media=await upload(f,`activities/${user.uid}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`);const s=$('#actSection').value;await upsert('activities','',{title:$('#actTitle').value.trim(),description:$('#actDescription').value.trim(),section:s,activityDate:$('#actDate').value,imageUrl:media.url,storagePath:media.path,status:sectionAllowed(s)?'approved':'pending'});e.target.reset();toast('Aktiviti berjaya dihantar.')}catch(e){toast(e.message)}}
async function saveUser(e){e.preventDefault();try{await FS.setDoc(FS.doc(db,'users',$('#userUid').value.trim()),{name:$('#userName').value.trim(),role:$('#userRole').value,status:$('#userStatus').value,updatedAt:FS.serverTimestamp(),updatedBy:user.uid},{merge:true});e.target.reset();toast('Peranan pengguna disimpan.')}catch(e){toast(e.message)}}
function listen(col,order='createdAt'){FS.onSnapshot(FS.query(FS.collection(db,col),FS.orderBy(order,'desc')),s=>{rows[col]=s.docs.map(d=>({id:d.id,...d.data()}));render(col)},e=>console.warn(col,e.message))}function subscribe(){listen('announcements');listen('news');listen('events','eventDate');listen('modules','order');listen('quickLinks','order');listen('activities');if(caps().users)listen('users','name');FS.onSnapshot(FS.doc(db,'settings','site'),s=>s.exists()&&fillSettings(s.data()))}
function actions(col,x){return `<button class="btn btn-small" onclick="editRow('${col}','${x.id}')">Edit</button> <button class="btn btn-danger btn-small" onclick="deleteRow('${col}','${x.id}')">Padam</button>`}function render(col){if(['announcements','news'].includes(col)){const all=[...rows.announcements.map(x=>({...x,_col:'announcements'})),...rows.news.map(x=>({...x,_col:'news'}))].sort((a,b)=>when(b.createdAt)-when(a.createdAt));$('#contentRows').innerHTML=all.map(x=>`<tr><td>${x._col==='news'?'Berita':'Pengumuman'}</td><td>${esc(x.title)}</td><td>${x.published?'Awam':'Draf'}</td><td>${actions(x._col,x)}</td></tr>`).join('');$('#countAnnouncements').textContent=rows.announcements.length;$('#countNews').textContent=rows.news.length}if(col==='events')$('#eventRows').innerHTML=rows.events.map(x=>`<tr><td>${esc(x.eventDate)}</td><td>${esc(x.title)}</td><td>${actions(col,x)}</td></tr>`).join('');if(col==='modules')$('#moduleRows').innerHTML=rows.modules.filter(x=>sectionAllowed(x.section)||['admin','gb'].includes(role())).map(x=>`<tr><td>${esc(x.section)}</td><td>${esc(x.icon)} ${esc(x.title)}</td><td>${actions(col,x)}</td></tr>`).join('');if(col==='quickLinks')$('#quickRows').innerHTML=rows.quickLinks.map(x=>`<tr><td>${esc(x.icon)} ${esc(x.label)}</td><td>${x.active?'Aktif':'Tutup'}</td><td>${actions(col,x)}</td></tr>`).join('');if(col==='activities'){const visible=rows.activities.filter(x=>['admin','gb'].includes(role())||x.createdBy===user.uid||sectionAllowed(x.section));$('#activityRows').innerHTML=visible.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.section)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${x.status==='pending'&&sectionAllowed(x.section)?`<button class="btn btn-green btn-small" onclick="approveActivity('${x.id}')">Lulus</button> `:''}${(sectionAllowed(x.section)||x.createdBy===user.uid)?`<button class="btn btn-danger btn-small" onclick="deleteActivity('${x.id}')">Padam</button>`:''}</td></tr>`).join('');$('#countActivities').textContent=rows.activities.length;$('#countPending').textContent=rows.activities.filter(x=>x.status==='pending').length}if(col==='users')$('#userRows').innerHTML=rows.users.map(x=>`<tr><td>${esc(x.name||x.id)}</td><td>${esc(x.role)}</td><td>${esc(x.status)}</td></tr>`).join('')}
function fillSettings(x){$('#schoolName').value=x.schoolName||'';$('#tagline').value=x.tagline||'';$('#motto').value=x.motto||'';$('#facebookUrl').value=x.facebookUrl||'';$('#phone').value=x.phone||'';$('#schoolEmail').value=x.email||'';$('#address').value=x.address||'';$('#vision').value=x.vision||'';$('#mission').value=x.mission||'';$('#primaryColor').value=x.primaryColor||'#0b4f8a';$('#secondaryColor').value=x.secondaryColor||'#1d7a4d';$('#accentColor').value=x.accentColor||'#f2c84b';$('#heroOverlay').value=x.heroOverlay||65;$('#overlayValue').textContent=`${x.heroOverlay||65}%`;const media=['logo','banner','pentadbiranBanner','kurikulumBanner','kokurikulumBanner','hemBanner','flag','plan'];media.forEach(key=>{const preview=$(`#${key}Preview`);if(x[`${key}Url`]&&preview){preview.src=x[`${key}Url`];preview.classList.remove('hidden')}})}
window.editRow=(col,id)=>{const x=rows[col].find(v=>v.id===id);if(!x)return;if(['announcements','news'].includes(col)){$('#contentId').value=id;$('#contentType').value=col;$('#contentTitle').value=x.title||'';$('#contentBody').value=x.body||x.summary||'';$('#contentPublished').checked=!!x.published;location.hash='content'}else if(col==='events'){$('#eventId').value=id;$('#eventTitle').value=x.title||'';$('#eventDescription').value=x.description||'';$('#eventDate').value=x.eventDate||'';$('#eventPublished').checked=!!x.published;location.hash='calendar'}else if(col==='modules'){$('#moduleId').value=id;$('#moduleSection').value=x.section;$('#moduleTitle').value=x.title||'';$('#moduleDescription').value=x.description||'';if($('#moduleContent'))$('#moduleContent').value=x.content||'';$('#moduleIcon').value=x.icon||'';$('#moduleUrl').value=x.url||'';$('#moduleOrder').value=x.order||0;$('#moduleActive').checked=!!x.active;location.hash='modules'}else if(col==='quickLinks'){$('#quickId').value=id;$('#quickLabel').value=x.label||'';$('#quickUrl').value=x.url||'';$('#quickIcon').value=x.icon||'';$('#quickOrder').value=x.order||0;$('#quickActive').checked=!!x.active;location.hash='quick'}};
window.deleteRow=async(col,id)=>{if(confirm('Padam item ini?'))try{await FS.deleteDoc(FS.doc(db,col,id));toast('Item dipadam.')}catch(e){toast(e.message)}};window.approveActivity=async id=>{try{await FS.updateDoc(FS.doc(db,'activities',id),{status:'approved',approvedAt:FS.serverTimestamp(),approvedBy:user.uid});toast('Aktiviti diluluskan.')}catch(e){toast(e.message)}};window.deleteActivity=async id=>{const x=rows.activities.find(v=>v.id===id);if(!x||!confirm('Padam aktiviti dan gambarnya?'))return;try{await FS.deleteDoc(FS.doc(db,'activities',id));if(x.storagePath)await ST.deleteObject(ST.ref(storage,x.storagePath)).catch(()=>{});toast('Aktiviti dipadam.')}catch(e){toast(e.message)}};
async function seedDefaultModules(){if(!['admin','gb'].includes(role()))return toast('Hanya Admin atau Guru Besar boleh menjalankan fungsi ini.');const button=$('#seedModulesBtn');button.disabled=true;button.textContent='Sedang memuatkan...';try{const batch=FS.writeBatch(db);let added=0;for(const [section,items] of Object.entries(defaultModules)){for(let i=0;i<items.length;i++){const [icon,title,description]=items[i];const slug=title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/&/g,'dan').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');const ref=FS.doc(db,'modules',`asal_${section}_${slug}`);const snap=await FS.getDoc(ref);if(!snap.exists()){batch.set(ref,{section,title,description,content:'',icon,url:'',order:(i+1)*10,active:true,source:'default-seed',createdAt:FS.serverTimestamp(),createdBy:user.uid,updatedAt:FS.serverTimestamp(),updatedBy:user.uid});added++}}}if(added)await batch.commit();toast(added?`${added} modul asal berjaya dimasukkan. Kini semua boleh diedit.`:'Semua modul asal sudah ada dalam Firebase.')}catch(e){toast('Modul tidak dapat dimuatkan: '+e.message)}finally{button.disabled=false;button.textContent='Muatkan Modul Asal ke Firebase'}}
const moduleUrlGroup=$('#moduleUrl')?.closest('.form-group');if(moduleUrlGroup){moduleUrlGroup.insertAdjacentHTML('beforebegin','<div class="form-group"><label>Isi penuh modul</label><textarea id="moduleContent" class="form-control" rows="7" placeholder="Masukkan penerangan, objektif, aktiviti, dokumen atau maklumat yang akan dibaca apabila kad ditekan."></textarea></div>')}
const moduleCard=$('#modules .card');if(moduleCard){moduleCard.insertAdjacentHTML('afterbegin','<div id="seedModulesBox" class="hidden" style="padding:14px 16px;margin-bottom:18px;border:1px solid #cfe1f1;border-radius:14px;background:#f3f9ff"><strong>Persediaan sekali sahaja</strong><p style="margin:6px 0 12px">Masukkan semua modul asal ke Firebase supaya ia muncul dalam senarai dan boleh diedit dari panel ini. Data yang sudah ada tidak akan ditindih.</p><button id="seedModulesBtn" type="button" class="btn btn-green">Muatkan Modul Asal ke Firebase</button></div>');$('#seedModulesBtn').addEventListener('click',seedDefaultModules)}
init();
